name: farming_solution_mobile
description: A Flutter mobile app for Farming Solution with crop price prediction, recommendations, and inventory management.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.1.4
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
